export interface PokemonGame {
  id: string;
  name: string;
  japaneseName?: string;
  releaseDate: string;
  region: string;
  generation: number;
  platform: string;
  coverImage: string;
  mapImage: string;
  description: string;
  features: string[];
  starters?: string[];
  legendaries?: string[];
  newPokemonCount?: number;
  totalPokemon?: number;
}

export const pokemonGames: PokemonGame[] = [
  {
    id: "red-green",
    name: "Pokémon Vert",
    japaneseName: "ポケットモンスター 赤・緑",
    releaseDate: "1996-02-27",
    region: "Kanto",
    generation: 1,
    platform: "Game Boy",
    coverImage: "/images/covers/pokemon_vert.png",
    mapImage: "/images/map/kanto.png",
    description: "Les tout premiers jeux Pokémon, sortis exclusivement au Japon. Ils ont lancé le phénomène mondial Pokémon.",
    features: ["151 Pokémon originaux", "Système de combat au tour par tour", "Échanges via câble Link", "8 badges d'arène"],
    starters: ["Bulbasaur", "Charmander", "Squirtle"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo"],
    newPokemonCount: 151,
    totalPokemon: 151
  },
  {
    id: "blue",
    name: "Pokémon Bleu",
    japaneseName: "ポケットモンスター 青",
    releaseDate: "1996-10-15",
    region: "Kanto",
    generation: 1,
    platform: "Game Boy",
    coverImage: "/images/covers/pokemon_bleu.png",
    mapImage: "/images/map/kanto.png",
    description: "Version améliorée de Rouge & Vert avec des sprites retravaillés et des corrections de bugs.",
    features: ["Sprites améliorés", "Corrections de bugs", "Même aventure dans Kanto"],
    starters: ["Bulbasaur", "Charmander", "Squirtle"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo"],
    newPokemonCount: 151,
    totalPokemon: 151
  },
  {
    id: "red",
    name: "Pokémon rouge",
    releaseDate: "1998-09-28",
    region: "Kanto",
    generation: 1,
    platform: "Game Boy",
    coverImage: "/images/covers/pokemon_rouge.png",
    mapImage: "/images/map/kanto.png",
    description: "Les versions internationales qui ont introduit Pokémon au monde entier.",
    features: ["Traduction internationale", "151 Pokémon", "Échanges et combats en multijoueur"],
    starters: ["Bulbasaur", "Charmander", "Squirtle"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo"],
    newPokemonCount: 151,
    totalPokemon: 151
  },
  {
    id: "yellow",
    name: "Pokémon Jaune",
    japaneseName: "ポケットモンスター ピカチュウ",
    releaseDate: "1998-09-12",
    region: "Kanto",
    generation: 1,
    platform: "Game Boy",
    coverImage: "/images/covers/pokemon_jaune.png",
    mapImage: "/images/map/kanto.png",
    description: "Version spéciale inspirée de l'anime où Pikachu vous suit partout.",
    features: ["Pikachu comme starter", "Pikachu vous suit", "Jessie & James apparaissent", "Obtention des 3 starters"],
    starters: ["Pikachu"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo"],
    newPokemonCount: 0,
    totalPokemon: 151
  },
  {
    id: "gold",
    name: "Pokémon Or",
    japaneseName: "ポケットモンスター 金・銀",
    releaseDate: "1999-11-21",
    region: "Johto",
    generation: 2,
    platform: "Game Boy Color",
    coverImage: "/images/covers/pokemon_or.png",
    mapImage: "/images/map/johto.jpg",
    description: "La deuxième génération introduit 100 nouveaux Pokémon, le cycle jour/nuit et les Pokémon chromatiques.",
    features: ["100 nouveaux Pokémon", "Cycle jour/nuit", "Pokémon chromatiques", "Reproduction", "Retour à Kanto"],
    starters: ["Chikorita", "Cyndaquil", "Totodile"],
    legendaries: ["Ho-Oh", "Lugia", "Raikou", "Entei", "Suicune", "Celebi"],
    newPokemonCount: 100,
    totalPokemon: 251
  },
  {
    id: "silver",
    name: "Pokémon Argent",
    japaneseName: "ポケットモンスター 金・銀",
    releaseDate: "1999-11-21",
    region: "Johto",
    generation: 2,
    platform: "Game Boy Color",
    coverImage: "/images/covers/pokemon_argent.png",
    mapImage: "/images/map/johto.jpg",
    description: "La deuxième génération introduit 100 nouveaux Pokémon, le cycle jour/nuit et les Pokémon chromatiques.",
    features: ["100 nouveaux Pokémon", "Cycle jour/nuit", "Pokémon chromatiques", "Reproduction", "Retour à Kanto"],
    starters: ["Chikorita", "Cyndaquil", "Totodile"],
    legendaries: ["Ho-Oh", "Lugia", "Raikou", "Entei", "Suicune", "Celebi"],
    newPokemonCount: 100,
    totalPokemon: 251
  },
  {
    id: "crystal",
    name: "Pokémon Cristal",
    japaneseName: "ポケットモンスター クリスタル",
    releaseDate: "2000-12-14",
    region: "Johto",
    generation: 2,
    platform: "Game Boy Color",
    coverImage: "/images/covers/pokemon_cristal.png",
    mapImage: "/images/map/johto.jpg",
    description: "Version améliorée avec des sprites animés et la possibilité de jouer une fille.",
    features: ["Sprites animés", "Personnage féminin jouable", "Histoire de Suicune", "Battle Tower"],
    starters: ["Chikorita", "Cyndaquil", "Totodile"],
    legendaries: ["Ho-Oh", "Lugia", "Suicune", "Celebi"],
    newPokemonCount: 0,
    totalPokemon: 251
  },
  {
    id: "sapphire",
    name: "Pokémon Saphir",
    japaneseName: "ポケットモンスター ルビー・サファイア",
    releaseDate: "2002-11-21",
    region: "Hoenn",
    generation: 3,
    platform: "Game Boy Advance",
    coverImage: "/images/covers/pokemon_saphir.png",
    mapImage: "/images/map/hoenn.png",
    description: "La troisième génération avec 135 nouveaux Pokémon, les combats doubles et les talents.",
    features: ["135 nouveaux Pokémon", "Combats doubles", "Talents", "Natures", "Concours Pokémon", "Bases secrètes"],
    starters: ["Treecko", "Torchic", "Mudkip"],
    legendaries: ["Groudon", "Kyogre", "Rayquaza", "Latias", "Latios", "Jirachi", "Deoxys"],
    newPokemonCount: 135,
    totalPokemon: 386
  },
  {
    id: "ruby",
    name: "Pokémon Rubis",
    japaneseName: "ポケットモンスター ルビー・サファイア",
    releaseDate: "2002-11-21",
    region: "Hoenn",
    generation: 3,
    platform: "Game Boy Advance",
    coverImage: "/images/covers/pokemon_rubis.png",
    mapImage: "/images/map/hoenn.png",
    description: "La troisième génération avec 135 nouveaux Pokémon, les combats doubles et les talents.",
    features: ["135 nouveaux Pokémon", "Combats doubles", "Talents", "Natures", "Concours Pokémon", "Bases secrètes"],
    starters: ["Treecko", "Torchic", "Mudkip"],
    legendaries: ["Groudon", "Kyogre", "Rayquaza", "Latias", "Latios", "Jirachi", "Deoxys"],
    newPokemonCount: 135,
    totalPokemon: 386
  },
  {
    id: "firere",
    name: "Pokémon Rouge Feu",
    japaneseName: "ポケットモンスター ファイアレッド・リーフグリーン",
    releaseDate: "2004-01-29",
    region: "Hoenn",
    generation: 3,
    platform: "Game Boy Advance",
    coverImage: "/images/covers/pokemon_rouge_feu.png",
    mapImage: "/images/map/hoenn.png",
    description: "Remakes des jeux originaux avec les graphismes et mécaniques de la 3ème génération.",
    features: ["Remake de Rouge & Bleu", "Îles Sevii", "Graphismes améliorés", "Wireless Adapter"],
    starters: ["Bulbasaur", "Charmander", "Squirtle"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo"],
    newPokemonCount: 0,
    totalPokemon: 386
  },
  {
    id: "leafgreen",
    name: "Pokémon Vert Feuille",
    japaneseName: "ポケットモンスター ファイアレッド・リーフグリーン",
    releaseDate: "2004-01-29",
    region: "Hoenn",
    generation: 3,
    platform: "Game Boy Advance",
    coverImage: "/images/covers/pokemon_vert_feuille.png",
    mapImage: "/images/map/hoenn.png",
    description: "Remakes des jeux originaux avec les graphismes et mécaniques de la 3ème génération.",
    features: ["Remake de Rouge & Bleu", "Îles Sevii", "Graphismes améliorés", "Wireless Adapter"],
    starters: ["Bulbasaur", "Charmander", "Squirtle"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo"],
    newPokemonCount: 0,
    totalPokemon: 386
  },
  {
    id: "emerald",
    name: "Pokémon Émeraude",
    japaneseName: "ポケットモンスター エメラルド",
    releaseDate: "2004-09-16",
    region: "Hoenn",
    generation: 3,
    platform: "Game Boy Advance",
    coverImage: "/images/covers/pokemon_emeraude.png",
    mapImage: "/images/map/hoenn.png",
    description: "Version définitive de Rubis & Saphir avec la Battle Frontier et une histoire enrichie.",
    features: ["Battle Frontier", "Histoire enrichie", "Rayquaza central", "Animations en combat"],
    starters: ["Treecko", "Torchic", "Mudkip"],
    legendaries: ["Groudon", "Kyogre", "Rayquaza"],
    newPokemonCount: 0,
    totalPokemon: 386
  },
  {
    id: "pearl",
    name: "Pokémon Perle",
    japaneseName: "ポケットモンスター ダイヤモンド・パール",
    releaseDate: "2006-09-28",
    region: "Sinnoh",
    generation: 4,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_perle.png",
    mapImage: "/images/map/sinnoh.png",
    description: "La quatrième génération en 3D avec le Wi-Fi et 107 nouveaux Pokémon.",
    features: ["107 nouveaux Pokémon", "Combats Wi-Fi", "GTS", "Écran tactile", "Souterrain"],
    starters: ["Turtwig", "Chimchar", "Piplup"],
    legendaries: ["Dialga", "Palkia", "Giratina", "Heatran", "Regigigas", "Cresselia", "Darkrai", "Shaymin", "Arceus"],
    newPokemonCount: 107,
    totalPokemon: 493
  },
  {
    id: "diamond",
    name: "Pokémon Diamant",
    japaneseName: "ポケットモンスター ダイヤモンド・パール",
    releaseDate: "2006-09-28",
    region: "Sinnoh",
    generation: 4,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_diamant.png",
    mapImage: "/images/map/sinnoh.png",
    description: "La quatrième génération en 3D avec le Wi-Fi et 107 nouveaux Pokémon.",
    features: ["107 nouveaux Pokémon", "Combats Wi-Fi", "GTS", "Écran tactile", "Souterrain"],
    starters: ["Turtwig", "Chimchar", "Piplup"],
    legendaries: ["Dialga", "Palkia", "Giratina", "Heatran", "Regigigas", "Cresselia", "Darkrai", "Shaymin", "Arceus"],
    newPokemonCount: 107,
    totalPokemon: 493
  },
  {
    id: "platinum",
    name: "Pokémon Platine",
    japaneseName: "ポケットモンスター プラチナ",
    releaseDate: "2008-09-13",
    region: "Sinnoh",
    generation: 4,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_platine.png",
    mapImage: "/images/map/sinnoh.png",
    description: "Version améliorée avec le Monde Distorsion et de nombreux ajouts.",
    features: ["Monde Distorsion", "Giratina forme Origine", "Zone de Combat", "Wi-Fi Plaza"],
    starters: ["Turtwig", "Chimchar", "Piplup"],
    legendaries: ["Dialga", "Palkia", "Giratina"],
    newPokemonCount: 0,
    totalPokemon: 493
  },
  {
    id: "heartgol",
    name: "Pokémon Or HeartGold",
    japaneseName: "ポケットモンスター ハートゴールド・ソウルシルバー",
    releaseDate: "2009-09-12",
    region: "Sinnoh",
    generation: 4,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_or_heartgold.png",
    mapImage: "/images/map/sinnoh.png",
    description: "Remakes adorés de Or & Argent avec le Pokéwalker et les Pokémon qui vous suivent.",
    features: ["Pokémon vous suivent", "Pokéwalker inclus", "Johto et Kanto", "Safari Zone amélioré"],
    starters: ["Chikorita", "Cyndaquil", "Totodile"],
    legendaries: ["Ho-Oh", "Lugia", "Suicune"],
    newPokemonCount: 0,
    totalPokemon: 493
  },
  {
    id: "soulsilver",
    name: "Pokémon Argent SoulSilver",
    japaneseName: "ポケットモンスター ハートゴールド・ソウルシルバー",
    releaseDate: "2009-09-12",
    region: "Sinnoh",
    generation: 4,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_argent_soulsilver.png",
    mapImage: "/images/map/sinnoh.png",
    description: "Remakes adorés de Or & Argent avec le Pokéwalker et les Pokémon qui vous suivent.",
    features: ["Pokémon vous suivent", "Pokéwalker inclus", "Johto et Kanto", "Safari Zone amélioré"],
    starters: ["Chikorita", "Cyndaquil", "Totodile"],
    legendaries: ["Ho-Oh", "Lugia", "Suicune"],
    newPokemonCount: 0,
    totalPokemon: 493
  },
  {
    id: "white",
    name: "Pokémon Blanc",
    japaneseName: "ポケットモンスター ブラック・ホワイト",
    releaseDate: "2010-09-18",
    region: "Unova",
    generation: 5,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_blanc.png",
    mapImage: "/images/map/unova.png",
    description: "La cinquième génération avec 156 nouveaux Pokémon et une histoire mature.",
    features: ["156 nouveaux Pokémon", "Histoire profonde", "Saisons", "Triple et Rotation battles", "Dream World"],
    starters: ["Snivy", "Tepig", "Oshawott"],
    legendaries: ["Reshiram", "Zekrom", "Kyurem", "Victini", "Cobalion", "Terrakion", "Virizion"],
    newPokemonCount: 156,
    totalPokemon: 649
  },
  {
    id: "black",
    name: "Pokémon Noir",
    japaneseName: "ポケットモンスター ブラック・ホワイト",
    releaseDate: "2010-09-18",
    region: "Unova",
    generation: 5,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_noir.png",
    mapImage: "/images/map/unova.png",
    description: "La cinquième génération avec 156 nouveaux Pokémon et une histoire mature.",
    features: ["156 nouveaux Pokémon", "Histoire profonde", "Saisons", "Triple et Rotation battles", "Dream World"],
    starters: ["Snivy", "Tepig", "Oshawott"],
    legendaries: ["Reshiram", "Zekrom", "Kyurem", "Victini", "Cobalion", "Terrakion", "Virizion"],
    newPokemonCount: 156,
    totalPokemon: 649
  },
  {
    id: "black2",
    name: "Pokémon Noir 2",
    japaneseName: "ポケットモンスター ブラック2・ホワイト2",
    releaseDate: "2012-06-23",
    region: "Unova",
    generation: 5,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_noir_2.jpeg",
    mapImage: "/images/map/unova.png",
    description: "Premières vraies suites directes, 2 ans après Noir & Blanc.",
    features: ["Suite directe", "Nouveau scénario", "PokéStar Studios", "Pokémon World Tournament"],
    starters: ["Snivy", "Tepig", "Oshawott"],
    legendaries: ["Reshiram", "Zekrom", "Kyurem"],
    newPokemonCount: 0,
    totalPokemon: 649
  },
  {
    id: "white2",
    name: "Pokémon Blanc 2",
    japaneseName: "ポケットモンスター ブラック2・ホワイト2",
    releaseDate: "2012-06-23",
    region: "Unova",
    generation: 5,
    platform: "Nintendo DS",
    coverImage: "/images/covers/pokemon_blanc_2.jpeg",
    mapImage: "/images/map/unova.png",
    description: "Premières vraies suites directes, 2 ans après Noir & Blanc.",
    features: ["Suite directe", "Nouveau scénario", "PokéStar Studios", "Pokémon World Tournament"],
    starters: ["Snivy", "Tepig", "Oshawott"],
    legendaries: ["Reshiram", "Zekrom", "Kyurem"],
    newPokemonCount: 0,
    totalPokemon: 649
  },
  {
    id: "x",
    name: "Pokémon X",
    japaneseName: "ポケットモンスター X・Y",
    releaseDate: "2013-10-12",
    region: "Kalos",
    generation: 6,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_x.png",
    mapImage: "/images/map/kalos.png",
    description: "Première génération entièrement en 3D avec les Méga-Évolutions et le type Fée.",
    features: ["72 nouveaux Pokémon", "Méga-Évolutions", "Type Fée", "Pokémon-Amie", "Super Entraînement", "Customisation du personnage"],
    starters: ["Chespin", "Fennekin", "Froakie"],
    legendaries: ["Xerneas", "Yveltal", "Zygarde", "Diancie", "Hoopa", "Volcanion"],
    newPokemonCount: 72,
    totalPokemon: 721
  },
  {
    id: "y",
    name: "Pokémon Y",
    japaneseName: "ポケットモンスター X・Y",
    releaseDate: "2013-10-12",
    region: "Kalos",
    generation: 6,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_y.png",
    mapImage: "/images/map/kalos.png",
    description: "Première génération entièrement en 3D avec les Méga-Évolutions et le type Fée.",
    features: ["72 nouveaux Pokémon", "Méga-Évolutions", "Type Fée", "Pokémon-Amie", "Super Entraînement", "Customisation du personnage"],
    starters: ["Chespin", "Fennekin", "Froakie"],
    legendaries: ["Xerneas", "Yveltal", "Zygarde", "Diancie", "Hoopa", "Volcanion"],
    newPokemonCount: 72,
    totalPokemon: 721
  },
  {
    id: "omega-ruby",
    name: "Pokémon Rubis Oméga",
    japaneseName: "ポケットモンスター オメガルビー・アルファサファイア",
    releaseDate: "2014-11-21",
    region: "Kalos",
    generation: 6,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_rubis_omega.png",
    mapImage: "/images/map/kalos.png",
    description: "Remakes sublimes de Rubis & Saphir avec la Vol Libre et le Primo-Retour.",
    features: ["Primo-Résurgence", "Vol Libre", "DexNav", "Bases secrètes améliorées", "Épisode Delta"],
    starters: ["Treecko", "Torchic", "Mudkip"],
    legendaries: ["Groudon", "Kyogre", "Rayquaza", "Deoxys"],
    newPokemonCount: 0,
    totalPokemon: 721
  },
  {
    id: "alpha-sapphire",
    name: "Pokémon Saphir Alpha",
    japaneseName: "ポケットモンスター オメガルビー・アルファサファイア",
    releaseDate: "2014-11-21",
    region: "Kalos",
    generation: 6,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_saphir_alpha.png",
    mapImage: "/images/map/kalos.png",
    description: "Remakes sublimes de Rubis & Saphir avec la Vol Libre et le Primo-Retour.",
    features: ["Primo-Résurgence", "Vol Libre", "DexNav", "Bases secrètes améliorées", "Épisode Delta"],
    starters: ["Treecko", "Torchic", "Mudkip"],
    legendaries: ["Groudon", "Kyogre", "Rayquaza", "Deoxys"],
    newPokemonCount: 0,
    totalPokemon: 721
  },
  {
    id: "sun",
    name: "Pokémon Soleil",
    japaneseName: "ポケットモンスター サン・ムーン",
    releaseDate: "2016-11-18",
    region: "Alola",
    generation: 7,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_soleil.png",
    mapImage: "/images/map/alola.png",
    description: "La septième génération dans un paradis tropical avec les Capacités Z et formes régionales.",
    features: ["81 nouveaux Pokémon", "Capacités Z", "Formes d'Alola", "Tour des Îles", "Poké Détente", "Festival Plaza"],
    starters: ["Rowlet", "Litten", "Popplio"],
    legendaries: ["Solgaleo", "Lunala", "Necrozma", "Cosmog", "Cosmoem"],
    newPokemonCount: 81,
    totalPokemon: 802
  },
  {
    id: "moon",
    name: "Pokémon Lune",
    japaneseName: "ポケットモンスター サン・ムーン",
    releaseDate: "2016-11-18",
    region: "Alola",
    generation: 7,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_lune.png",
    mapImage: "/images/map/alola.png",
    description: "La septième génération dans un paradis tropical avec les Capacités Z et formes régionales.",
    features: ["81 nouveaux Pokémon", "Capacités Z", "Formes d'Alola", "Tour des Îles", "Poké Détente", "Festival Plaza"],
    starters: ["Rowlet", "Litten", "Popplio"],
    legendaries: ["Solgaleo", "Lunala", "Necrozma", "Cosmog", "Cosmoem"],
    newPokemonCount: 81,
    totalPokemon: 802
  },
  {
    id: "ultra-sun",
    name: "Pokémon Ultra-Soleil",
    japaneseName: "ポケットモンスター ウルトラサン・ウルトラムーン",
    releaseDate: "2017-11-17",
    region: "Alola",
    generation: 7,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_ultra-soleil.jpg",
    mapImage: "/images/map/alola.png",
    description: "Versions enrichies avec les Ultra-Chimères et un scénario alternatif.",
    features: ["Nouvelle histoire", "Ultra-Brèches", "Plus d'Ultra-Chimères", "Team Rainbow Rocket", "Photo Club"],
    starters: ["Rowlet", "Litten", "Popplio"],
    legendaries: ["Solgaleo", "Lunala", "Necrozma"],
    newPokemonCount: 5,
    totalPokemon: 807
  },
  {
    id: "ultra-moon",
    name: "Pokémon Ultra-Lune",
    japaneseName: "ポケットモンスター ウルトラサン・ウルトラムーン",
    releaseDate: "2017-11-17",
    region: "Alola",
    generation: 7,
    platform: "Nintendo 3DS",
    coverImage: "/images/covers/pokemon_ultra-lune.jpg",
    mapImage: "/images/map/alola.png",
    description: "Versions enrichies avec les Ultra-Chimères et un scénario alternatif.",
    features: ["Nouvelle histoire", "Ultra-Brèches", "Plus d'Ultra-Chimères", "Team Rainbow Rocket", "Photo Club"],
    starters: ["Rowlet", "Litten", "Popplio"],
    legendaries: ["Solgaleo", "Lunala", "Necrozma"],
    newPokemonCount: 5,
    totalPokemon: 807
  },
  {
    id: "lets-go-pikachu",
    name: "Pokémon Let's Go Pikachu",
    japaneseName: "ポケットモンスター Let's Go! ピカチュウ・Let's Go! イーブイ",
    releaseDate: "2018-11-16",
    region: "Kanto",
    generation: 7,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_lets_go_pikachu.png",
    mapImage: "/images/map/alola.png",
    description: "Remake de Jaune avec les mécaniques de capture de Pokémon GO.",
    features: ["Capture style GO", "Pokémon visibles", "Jeu coopératif", "Pokéball Plus compatible", "Connexion Pokémon GO"],
    starters: ["Pikachu", "Eevee"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo", "Meltan", "Melmetal"],
    newPokemonCount: 2,
    totalPokemon: 153
  },
  {
    id: "lets-go-eevee",
    name: "Pokémon Let's Go Évoli",
    japaneseName: "ポケットモンスター Let's Go! ピカチュウ・Let's Go! イーブイ",
    releaseDate: "2018-11-16",
    region: "Kanto",
    generation: 7,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_lets_go_evoli.png",
    mapImage: "/images/map/alola.png",
    description: "Remake de Jaune avec les mécaniques de capture de Pokémon GO.",
    features: ["Capture style GO", "Pokémon visibles", "Jeu coopératif", "Pokéball Plus compatible", "Connexion Pokémon GO"],
    starters: ["Pikachu", "Eevee"],
    legendaries: ["Articuno", "Zapdos", "Moltres", "Mewtwo", "Meltan", "Melmetal"],
    newPokemonCount: 2,
    totalPokemon: 153
  },
  {
    id: "sword",
    name: "Pokémon Épée",
    japaneseName: "ポケットモンスター ソード・シールド",
    releaseDate: "2019-11-15",
    region: "Galar",
    generation: 8,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_epée.png",
    mapImage: "/images/map/galar.png",
    description: "La huitième génération avec les Terres Sauvages et le phénomène Dynamax.",
    features: ["81 nouveaux Pokémon", "Dynamax/Gigamax", "Terres Sauvages", "Raids Max", "Camp Pokémon"],
    starters: ["Grookey", "Scorbunny", "Sobble"],
    legendaries: ["Zacian", "Zamazenta", "Eternatus", "Kubfu", "Zarude"],
    newPokemonCount: 81,
    totalPokemon: 898
  },
  {
    id: "shield",
    name: "Pokémon Bouclier",
    japaneseName: "ポケットモンスター ソード・シールド",
    releaseDate: "2019-11-15",
    region: "Galar",
    generation: 8,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_bouclier.png",
    mapImage: "/images/map/galar.png",
    description: "La huitième génération avec les Terres Sauvages et le phénomène Dynamax.",
    features: ["81 nouveaux Pokémon", "Dynamax/Gigamax", "Terres Sauvages", "Raids Max", "Camp Pokémon"],
    starters: ["Grookey", "Scorbunny", "Sobble"],
    legendaries: ["Zacian", "Zamazenta", "Eternatus", "Kubfu", "Zarude"],
    newPokemonCount: 81,
    totalPokemon: 898
  },
  {
    id: "brilliant-diamond",
    name: "Pokémon Diamant Étincelant",
    japaneseName: "ポケットモンスター ブリリアントダイヤモンド・シャイニングパール",
    releaseDate: "2021-11-19",
    region: "Sinnoh",
    generation: 8,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_diamant_etincelant.png",
    mapImage: "/images/map/galar.png",
    description: "Remakes fidèles de Diamant & Perle avec un style chibi charmant.",
    features: ["Style graphique chibi", "Grand Souterrain", "Parc Rosa Rugosa", "Fidèle aux originaux"],
    starters: ["Turtwig", "Chimchar", "Piplup"],
    legendaries: ["Dialga", "Palkia", "Giratina"],
    newPokemonCount: 0,
    totalPokemon: 493
  },
  {
    id: "shining-pearl",
    name: "Pokémon Perle Scintillante",
    japaneseName: "ポケットモンスター ブリリアントダイヤモンド・シャイニングパール",
    releaseDate: "2021-11-19",
    region: "Sinnoh",
    generation: 8,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_perle_scintillante.png",
    mapImage: "/images/map/galar.png",
    description: "Remakes fidèles de Diamant & Perle avec un style chibi charmant.",
    features: ["Style graphique chibi", "Grand Souterrain", "Parc Rosa Rugosa", "Fidèle aux originaux"],
    starters: ["Turtwig", "Chimchar", "Piplup"],
    legendaries: ["Dialga", "Palkia", "Giratina"],
    newPokemonCount: 0,
    totalPokemon: 493
  },
  {
    id: "legends-arceus",
    name: "Légendes Pokémon : Arceus",
    japaneseName: "Pokémon LEGENDS アルセウス",
    releaseDate: "2022-01-28",
    region: "Hisui",
    generation: 8,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_arceus.png",
    mapImage: "/images/map/galar.png",
    description: "Jeu révolutionnaire en monde semi-ouvert dans le Sinnoh ancestral.",
    features: ["Monde semi-ouvert", "Système de capture innovant", "Pokémon Nobles", "Formes Hisui", "Quête Pokédex active"],
    starters: ["Rowlet", "Cyndaquil", "Oshawott"],
    legendaries: ["Arceus", "Dialga", "Palkia", "Giratina"],
    newPokemonCount: 7,
    totalPokemon: 242
  },
  {
    id: "scarlet",
    name: "Pokémon Écarlate",
    japaneseName: "ポケットモンスター スカーレット・バイオレット",
    releaseDate: "2022-11-18",
    region: "Paldea",
    generation: 9,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_ecarlate.png",
    mapImage: "/images/map/paldea.png",
    description: "Premier vrai monde ouvert Pokémon avec trois aventures entrelacées.",
    features: ["Monde ouvert complet", "Téracristallisation", "Trois scénarios", "Raids Téracristal", "Coopération 4 joueurs"],
    starters: ["Sprigatito", "Fuecoco", "Quaxly"],
    legendaries: ["Koraidon", "Miraidon", "Chien-Pao", "Chi-Yu", "Ting-Lu", "Wo-Chien"],
    newPokemonCount: 103,
    totalPokemon: 1008
  },
  {
    id: "violet",
    name: "Pokémon Violet",
    japaneseName: "ポケットモンスター スカーレット・バイオレット",
    releaseDate: "2022-11-18",
    region: "Paldea",
    generation: 9,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_violet.png",
    mapImage: "/images/map/paldea.png",
    description: "Premier vrai monde ouvert Pokémon avec trois aventures entrelacées.",
    features: ["Monde ouvert complet", "Téracristallisation", "Trois scénarios", "Raids Téracristal", "Coopération 4 joueurs"],
    starters: ["Sprigatito", "Fuecoco", "Quaxly"],
    legendaries: ["Koraidon", "Miraidon", "Chien-Pao", "Chi-Yu", "Ting-Lu", "Wo-Chien"],
    newPokemonCount: 103,
    totalPokemon: 1008
  },
  {
    id: "legends-za",
    name: "Légendes Pokémon : Z-A",
    japaneseName: "Pokémon LEGENDS Z-A",
    releaseDate: "2025-01-01",
    region: "Kalos",
    generation: 9,
    platform: "Nintendo Switch",
    coverImage: "/images/covers/pokemon_z-a.png",
    mapImage: "/images/map/paldea.png",
    description: "Nouvelle aventure dans la ville de Lumiose en pleine rénovation urbaine.",
    features: ["Entièrement à Lumiose", "Projet de rénovation urbaine", "Méga-Évolutions", "À venir en 2025"],
    starters: ["À confirmer"],
    legendaries: ["Zygarde"],
    newPokemonCount: 0,
    totalPokemon: 0
  }
];

export const getGameById = (id: string | string[]): PokemonGame | undefined => {
  return pokemonGames.find(game => game.id === id);
};

export const getGamesByGeneration = (generation: number): PokemonGame[] => {
  return pokemonGames.filter(game => game.generation === generation);
};

export const getGamesByPlatform = (platform: string): PokemonGame[] => {
  return pokemonGames.filter(game => game.platform === platform);
};

export const sortGamesByDate = (games: PokemonGame[]): PokemonGame[] => {
  return [...games].sort((a, b) => new Date(a.releaseDate).getTime() - new Date(b.releaseDate).getTime());
};

export const getPlatformColor = (platform: string): string => {
  const colors: Record<string, string> = {
    "Game Boy": "from-green-600 to-green-400",
    "Game Boy Color": "from-purple-600 to-purple-400",
    "Game Boy Advance": "from-indigo-600 to-indigo-400",
    "Nintendo DS": "from-gray-600 to-gray-400",
    "Nintendo 3DS": "from-red-600 to-red-400",
    "Nintendo Switch": "from-red-500 to-blue-500"
  };
  return colors[platform] || "from-gray-600 to-gray-400";
};

export const getGenerationColor = (generation: number): string => {
  const colors: Record<number, string> = {
    1: "from-red-500 to-blue-500",
    2: "from-yellow-500 to-gray-500",
    3: "from-red-600 to-blue-600",
    4: "from-blue-400 to-pink-400",
    5: "from-gray-800 to-gray-100",
    6: "from-blue-500 to-red-500",
    7: "from-orange-500 to-purple-500",
    8: "from-cyan-500 to-pink-500",
    9: "from-orange-600 to-purple-600"
  };
  return colors[generation] || "from-gray-600 to-gray-400";
};
